function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Jul-2014 15:23:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineStyle','--');

% Create title
title({'Squares of values'});

% Create xlabel
xlabel({'Values'});

% Create ylabel
ylabel({'Values squared'});

